# Generated by Django 5.2.6 on 2025-09-23 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=20)),
                ('event_type', models.CharField(choices=[('new_lead', 'New Lead'), ('lead_status_change', 'Lead Status Change'), ('task_completion', 'Task Completion'), ('system_error', 'System Error'), ('daily_report', 'Daily Report'), ('weekly_report', 'Weekly Report')], max_length=30)),
                ('recipients', models.JSONField(default=list)),
                ('message_template', models.TextField()),
                ('subject_template', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('send_immediately', models.BooleanField(default=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('ai_personalization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_channels',
                'unique_together': {('channel_type', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('auto_posting_enabled', models.BooleanField(default=True)),
                ('posting_schedule', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('error', 'Error'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_posted', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_engagement', models.PositiveIntegerField(default=0)),
                ('average_engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'social_media_accounts',
                'unique_together': {('platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=50)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('document', 'Document'), ('voice', 'Voice'), ('video', 'Video'), ('sticker', 'Sticker')], default='text', max_length=20)),
                ('message_content', models.TextField()),
                ('media_file_id', models.CharField(blank=True, max_length=200)),
                ('telegram_message_id', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=50)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True)),
                ('is_inbound', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_command', models.BooleanField(default=False)),
                ('command_name', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_integration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('n8n', 'n8n Workflow'), ('zapier', 'Zapier'), ('crm', 'CRM System'), ('email_marketing', 'Email Marketing'), ('analytics', 'Analytics'), ('payment', 'Payment Gateway'), ('storage', 'Cloud Storage')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.TextField()),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('mapping_rules', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('expired', 'Expired')], default='active', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency_minutes', models.PositiveIntegerField(default=60)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'third_party_integrations',
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('endpoint', models.URLField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('response_status_code', models.PositiveIntegerField()),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='integrations.thirdpartyintegration')),
            ],
            options={
                'db_table': 'api_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('template', 'Template'), ('interactive', 'Interactive')], default='text', max_length=20)),
                ('message_content', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('template_parameters', models.JSONField(default=list)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True)),
                ('is_inbound', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('requires_response', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('response_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_integration',
                'ordering': ['-sent_at'],
            },
        ),
    ]
