# Generated by Django 5.2.6 on 2025-09-23 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_sources',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('lead_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='individual', max_length=20)),
                ('lead_quality', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=20)),
                ('interested_services', models.JSONField(default=list)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_insights', models.JSONField(default=dict)),
                ('predicted_conversion_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColdCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('language', models.CharField(default='en', max_length=10)),
                ('script_used', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail')], default='scheduled', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback_requested', 'Callback Requested'), ('information_requested', 'Information Requested'), ('meeting_scheduled', 'Meeting Scheduled')], max_length=30)),
                ('conversation_transcript', models.TextField(blank=True)),
                ('ai_sentiment_analysis', models.JSONField(default=dict)),
                ('ai_next_action', models.CharField(blank=True, max_length=200)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_calls', to='leads.lead')),
            ],
            options={
                'db_table': 'cold_call_logs',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('meeting', 'Meeting'), ('note', 'Note'), ('proposal', 'Proposal Sent'), ('follow_up', 'Follow Up'), ('status_change', 'Status Change')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('cold_call_script', 'Cold Call Script'), ('email_template', 'Email Template'), ('whatsapp_template', 'WhatsApp Template'), ('follow_up_template', 'Follow Up Template')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('both', 'Both')], default='en', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('personalized_content', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_communications',
                'ordering': ['-created_at'],
            },
        ),
    ]
